language: go
go:
  - '1.11.x'
sudo: required
services:
  - docker
install: .travis/install-pack.sh
script: .travis/create-builder.sh && make test
deploy:
  skip_cleanup: true
  provider: script
  script: .travis/push-to-dockerhub.sh && .travis/push-buildtemplate-to-gcs.sh
  on:
    branch: master