language: go
go:
- 1.13.x
cache:
  directories:
  - "$GOPATH/pkg/mod"
install: ".travis/install-pack.sh"
script: ".travis/create-builder.sh && make test"
deploy:
  skip_cleanup: true
  provider: script
  script: ".travis/push-to-dockerhub.sh && .travis/push-buildtemplate-to-gcs.sh"
  on:
    branch: master
notifications:
  slack:
    secure: kO//Ex1tuZqNV9lHZuX118p0ekv+ssrE4KTXEdQHu1rf9aXbQUmhgdaY7kILtuS8m1whbl/UC/nYOq9h7KUDicp9TUtiJBBydBj1IZqGZD2YBHfstxrzmGjQ3PqtDn2KRq4RjAQL+vUR8zHchD2GgxULKVZflVfH7UYWBfN2H+IPmVYOKdn3XmNI6j+lHUuwrE3LxijgqEB1pbEeZ9l2BRZX+YKAI+/0wnhH2823Tvu3Wi5oYjI7iWB9AKvMMCw86LwOQj9vbiL0335/q7HzvRa2mrEqkpoALnH0FWR7Kc0SGmzX4uHRfEu0gOWAEEyCVxBZNkAECLdUa6ShhuXqT+rmgqS5DC4txVavIl6p8KFLfnIrW4Fny1GO276kd3Q2RR/iGnJtOmrq77MhENkiyiVYJeIE+Ukjhr5hIeV9OM/bphRkJKoWQHsnJK6BlUNWOCITDOlSzL3gsgVuimIHX5KeVwvl1BYmFgdV37DeKiSBdRQmeZgwllAG5LniOEl0N/5Pc7MQ7Y9KGorCVdc33PDEs/c655cohXOrXd2OVr9LP/yyYYjNY8lOwa7twbWMQyzvT6SZG0DO0z0DyLbHER2CmUkw8q9GPKShAkbja9+mOoCMGGJSlOLGIb0t5RTNV21Q+rtlVCXkje6BQ9EIVdrPVFQ+F+3I8pN8ytZhtzE=
