[[testcases]]
repo = "https://github.com/projectriff-samples/fats-uppercase-java"
handler = "functions.Upper"
input = "builder"
content-type = "text/plain"
output = "BUILDER"

[[testcases]]
repo = "https://github.com/projectriff-samples/fats-uppercase-java-boot"
input = "builder"
content-type = "text/plain"
output = "BUILDER"

[[testcases]]
repo = "https://github.com/projectriff-samples/fats-uppercase-node"
artifact = "uppercase.js"
input = "builder"
content-type = "text/plain"
output = "BUILDER"

[[testcases]]
repo = "https://github.com/projectriff-samples/fats-uppercase-npm"
input = "builder"
content-type = "text/plain"
output = "BUILDER"

[[testcases]]
repo = "https://github.com/projectriff-samples/fats-uppercase-command"
artifact = "uppercase.sh"
input = "builder"
content-type = "text/plain"
output = "BUILDER"
